# Generated by Django 4.0.6 on 2022-07-25 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CpuTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=10)),
                ('studentID', models.IntegerField(default=0)),
                ('cool', models.BooleanField(default=False)),
            ],
        ),
    ]
